### ISSUE TITLE
I've packaged the go-spatial binaries on conda-forge for easier installation

### ISSUE THREAD

**Issue by dharhas** [jblindsay/go-spatial#3]
Hi,

Wanted to let you know that I have packaged the go-spatial binaries on the community conda-forge channel of the Anaconda distribution. Anaconda is a package manager used by a lot of folks doing Python/R data science and engineering type work.

Essentially all it does is install the correct binary (pulled from this repo) into your environment path for the platform you are on.

This allows for two things.

1) End user can install by using `conda install -c conda-forge go-spatial`
2) I can specify go-spatial as a dependency of other modules (including some python scripts I am writing) and it will be installed automagically.

If you would like to be added as a maintainer on the conda-forge go-spatial packaging repo, please let me know.

Links:
Anaconda: https://www.continuum.io/downloads
Conda-Forge: https://conda-forge.github.io/
go-spatial package repo: https://github.com/conda-forge/go-spatial-feedstock

**Comment by jblindsay** [comment]
Fantastic job and thanks for doing this!
