### ISSUE TITLE
D8 flow pointer raster?

### ISSUE THREAD

**Issue by dharhas** [jblindsay/go-spatial#4]
I need to do a watershed delineation, I don't see a way to save the d8 directions raster so I can do the delineation from a pour/outlet point. I'm assuming this is calculated somewhere in the d8flowaccumulation tool. Is there a way to output this data.

**Comment by folcred** [comment]
I have a similar problem. I need the flow pointer in order to convert raster streams to vector.

**Comment by jblindsay** [comment]
While I do not currently have any plans to add the Watershed tool nor the D8FlowDirection tool to GoSpatial, I am currently re-writing all of Whitebox GAT's tools in the Rust programming language. In this way, people will be able to access the tools from outside of the Whitebox GAT user interface. In fact, while this is a long-term project, I have already ported the Watershed and D8FlowDirection tools over (see [WhiteboxTools](https://github.com/jblindsay/whitebox-geospatial-analysis-tools/tree/master/whitebox_tools). If this is your primary interest in porting these tools over to GoSpatial, I suggest that you take a look at WhiteboxTools instead.

**Comment by dharhas** [comment]
@jblindsay thanks. I'll have a look at WhiteBoxTools.
