### ISSUE TITLE
Port Whitebox Watershed.java?

### ISSUE THREAD

**Issue by johnniehard** [jblindsay/go-spatial#6]
I'm interested in having access to the [watershed tool](https://github.com/jblindsay/whitebox-geospatial-analysis-tools/blob/master/HydroTools/src/plugins/Watershed.java) from Whitebox GAT. The algorithm doesn't look too complilcated, but I have not written Go before. I wouldn't mind taking the time to learn, but may need some pointers.

Would a port be possible? Are there any obvious hurdles?

**Comment by jblindsay** [comment]
While I do not currently have any plans to add the Watershed tool to GoSpatial, I am currently re-writing all of Whitebox GAT's tools in Rust. In this way, people will be able to access the tools from outside of the Whitebox GAT user interface. In fact, while this is a long-term project, I have already ported the Watershed tool over (see [WhiteboxTools](https://github.com/jblindsay/whitebox-geospatial-analysis-tools/tree/master/whitebox_tools). If this is your primary interest in porting the tool over to GoSpatial, I suggest that you take a look at WhiteboxTools instead.
